---
name: "Delete container versions"

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: "Package name"
        default: ""
        required: true

jobs:
  delete-versions:
    name: Delete versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: "${{ github.event.inputs.packageName }}"
          package-type: container
          num-old-versions-to-delete: 100
          min-versions-to-keep: 0
